apiVersion: v1
kind: List
items:
{{range $app := .Values.apps }}
  - apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: {{ $app.name }}
    spec:
      project: default
      source:
        helm:
          valueFiles:
          {{ range $valueFile := $app.valueFiles }}
          - {{ . }}
          {{ end }}
        path: {{ $app.path }}
        repoURL:  {{ $app.repoUrl }}
        targetRevision: {{ $app.revision }}
      destination:
        namespace:  {{ $app.namespace }}
        server: {{ $app.server }}
      syncPolicy:
        automated:
          prune: true
        syncOptions:
        - CreateNamespace=true
{{end}}