apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ .Values.application.name }}
  labels:
    job: {{ .Values.application.jobId }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.application.name }}
  replicas: {{ default 1 .Values.application.count | int }}
  template:
    metadata:
      labels:
        app: {{ .Values.application.name }}
    spec:
      containers:
      - name: {{ .Values.application.name  }}
        image: "{{ .Values.application.image }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.application.port | int }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.application.port | int }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.application.port | int }}
        resources:
          limits:
            cpu: {{ .Values.resources.cpu | int }}
            memory: {{ .Values.resources.memory | int }}
          requests:
            cpu: {{ .Values.resources.cpu | int }}
            memory: {{ .Values.resources.memory | int }}