{{- $chartname := .Chart.Name }}
{{- $chartversion := .Chart.Version }}
{{- range $service := .Values.services }}
{{- if $service.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name:  {{ $service.name}}
  labels:
    chart: "{{ $chartname }}-{{ $chartversion | replace "+" "_" }}"
spec:
  selector:
    matchLabels:
      app:  {{ $service.name}}
  replicas: {{ default 1 $service.replicaCount | int }}
  template:
    metadata:
      labels:
        app:  {{ $service.name}}
    spec:
      {{ if $service.storage }}
      volumes:
      {{ range $index,$spec := $service.storage }}
      - name: {{ $service.name }}{{ $index }}
        persistentVolumeClaim:
            claimName: {{ $service.name }}{{ $index }}
      {{ end }}
      {{ end }}
      containers:
      - name: "{{ $chartname }}-{{ $service.name}}"
        image: "{{ $service.image }}"
        {{if $service.security}}
        securityContext:
          {{ if $service.sysctls }}
          sysctls:
            {{ range $key,$value := $service.sysctls }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{ end }}
          {{end}}
          {{ if $service.capabilities }}
            capabilities:
              {{if $service.capabilities.add }}
              add:
                {{range $capadd := $service.capabilities.add }}
                - {{ $capadd }}
                {{end}}
              {{end}}
          {{end}}
        {{ end }}
        imagePullPolicy: IfNotPresent
        {{ if $service.commands}}
        command: 
        {{range $cmd := $service.commands}}
          - {{ $cmd | quote}}
        {{ end }}
        {{end}}
        {{ if $service.args}}
        args: 
        {{range $args := $service.args}}
          - {{ $args | quote}}
        {{ end }}
        {{end}}
        {{ if $service.env }}
        env:
        {{ if $service.env.confidential }} 
        {{- range  $confidential := $service.env.confidential}}
        - name: {{ $confidential.exposed | quote }}
          valueFrom:
            secretKeyRef:
              name: {{ $confidential.secretName | quote }}
              key: {{ $confidential.key | quote }}
        {{end}}
        {{end}}
        {{- range $key,$value := $service.env }}
        - name: {{ $key | quote }}
          value: {{ $value | quote }}
        {{end}}
        {{end}}
        {{ if $service.service }}
        ports:
        {{ range $service.service.internalPort }}
        - containerPort: {{  . | int }}
        {{ end }}
        {{ end }}
        {{ if $service.storage }}
        volumeMounts:
        {{ range $index,$spec := $service.storage }}
        - mountPath: {{ $spec.path | quote }}
          name: {{ $service.name }}{{ $index }}
        {{ end }}
        {{ end }}
        resources:
{{ toYaml $service.resources | indent 10 }}
---
{{ end }}
{{ end }}