
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application.name }}
spec:
  type: ClusterIP
  ports:
  - port:  {{  .Values.application.port | int }}
    targetPort:  {{  .Values.application.port | int }}
    protocol: TCP
    name: {{ .Values.application.name  }}
  selector:
    app: {{ .Values.application.name }}
---
