
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.applicationName }}
spec:
  type: ClusterIP
  ports:
  - port:  {{  .Values.internalPort | int }}
    targetPort:  {{  .Values.internalPort | int }}
    protocol: TCP
    name: {{ .Values.applicationName  }}
  selector:
    app: {{ .Values.applicationName }}
---
