apps:
  - name: tenants
    valueFiles:
      - values-common-hcloud.yml
      - values-reporting21-hcloud.yml
    path: recette
    repoUrl: git@github.com/reporting21/reporting21-tenant.git
    revision: heztner
    namespace: argocd
    server: https://kubernetes.default.svc